# Generated docker-compose.yml
# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  frontend:
    image: frontend2
    container_name: frontend2
    build:
      context: ./cpt2/frontend
      dockerfile: Dockerfile
    ports:
      - 5000
      - 5001
    environment:
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
