# Generated docker-compose.yml
# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  frontend:
    image: frontend2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000
      - 5001
