# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: cpt2/frontend/Dockerfile
    ports:
      - 5000
      - 5001
